name: download
run-name: Download ${{ inputs.title }}.${{ inputs.ext }}

on:
  workflow_dispatch:
    inputs:
      url:
        description: "url"
        required: true
      title:
        description: "title"
        required: true
      ext:
        description: "ext"
        required: true
        default: "mp4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: |
        mkdir -p MyVideos
        sudo wget --no-check-certificate "${{ inputs.url }}" -O "MyVideos/${{ inputs.title }}.${{ inputs.ext }}"

    - name: Upload Wenshushu
      id: Wenshushu
      if: (!cancelled())
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wss --no-progress MyVideos 2>&1 | tee Wenshushu.log
        echo "::warning file=Wenshushu.cn::$(cat Wenshushu.log | grep https)"
        echo "æ–‡ä»¶åç§°ï¼šã€Š${{ inputs.video-title }}ã€‹" >> body.md
        echo "" >> body.md
        echo "ä¸‹è½½åœ°å€:ðŸ”— [Wenshushu]($(cat Wenshushu.log | grep https | cut -f3 -d" "))" >> body.md
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v1
      if: (!cancelled())
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.Wenshushu.outputs.release_tag }}
        body_path: body.md
